import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Textbook',
      items: [
        'introduction',
        {
          type: 'category',
          label: 'Foundations',
          items: [
            'chapter1',
            'intro-physical-ai',
            'humanoid-fundamentals',
            'kinematics-dynamics',
          ],
        },
        {
          type: 'category',
          label: 'Core Systems',
          items: [
            'control-systems',
            'ai-integration',
            'sensor-systems',
            'actuator-systems',
          ],
        },
        {
          type: 'category',
          label: 'Advanced Topics',
          items: [
            'learning-algorithms',
            'ethics-safety',
            'future-directions',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
